// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5B2c7aHwkUJhYrNrQbHJI_oepZC6DNSE',
    appId: '1:273962549900:web:de00e1f4d762e16dc131a9',
    messagingSenderId: '273962549900',
    projectId: 'whatsapp-clone-7db4f',
    authDomain: 'whatsapp-clone-7db4f.firebaseapp.com',
    storageBucket: 'whatsapp-clone-7db4f.appspot.com',
    measurementId: 'G-WMGK3E3XCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5N1dDmD-jdCclvIhQMwZiZFG6SqlqIyQ',
    appId: '1:273962549900:android:f472b083b34efec1c131a9',
    messagingSenderId: '273962549900',
    projectId: 'whatsapp-clone-7db4f',
    storageBucket: 'whatsapp-clone-7db4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxHjr_19lRhBCJQUVMMrXbHPenjgGQp4',
    appId: '1:273962549900:ios:9b354fc005c415d0c131a9',
    messagingSenderId: '273962549900',
    projectId: 'whatsapp-clone-7db4f',
    storageBucket: 'whatsapp-clone-7db4f.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxHjr_19lRhBCJQUVMMrXbHPenjgGQp4',
    appId: '1:273962549900:ios:197405202d43fd70c131a9',
    messagingSenderId: '273962549900',
    projectId: 'whatsapp-clone-7db4f',
    storageBucket: 'whatsapp-clone-7db4f.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
